version: 2.1
jobs:
  build:
    working_directory: ~/build-test # Where steps will run.
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install-project-dependencies
          command: npm install
      - run:
          name: test
          command: npm test