version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run:
          name: install-angular-cli
          command: 'sudo npm install -g angular-cli@latest'
      - run:
          name: install-project-dependencies
          command: npm install
      - run:
          name: test
          command: npm test